import { SkillTreeNode } from '../types';

export const FACE_NODES: SkillTreeNode[] = [
  // ─── TIER 1: TRỤ NGŨ QUAN & BIỂU CẢM ───
  {
    id: 'pillar_face',
    promptId: 'face_angle0_8s',
    title: 'Trụ Ngũ Quan & Biểu Cảm',
    shortLabel: 'Khuôn Mặt & Cảm Xúc',
    subtitle: 'Ngũ quan nền xanh 8s & các loạt biểu cảm đơn 4 góc',
    icon: '😊',
    iconPath: '/icons/pillar_face.svg',
    category: 'face',
    color: '#ec4899',
    tier: 1,
    x: -2692,
    y: 1508,
    parentId: 'root_master',
    isHub: true,
    badge: '38 PROMPTS',
  },

  // ─── 1. MASTER TIMELINE 8 GIÂY ───
  {
    id: 'hub_face_8s',
    promptId: 'face_angle0_8s',
    title: 'Master Timeline 8 Giây',
    shortLabel: '8s Master',
    subtitle: '1 prompt chứa 4 biểu cảm chuyển đổi theo giây',
    icon: '⏱️',
    iconPath: '/icons/skill_face_8s.svg',
    category: 'face',
    color: '#ec4899',
    tier: 2,
    x: -3511,
    y: 2064,
    parentId: 'pillar_face',
    isHub: true,
    badge: '4 GÓC MASTER',
  },
  { id: 'node_face_8s_0', promptId: 'face_angle0_8s', title: 'Face 8s 0°', shortLabel: 'Face 0° 8s', icon: '⬇️', iconPath: '/icons/skill_face_8s.svg', category: 'face', color: '#ec4899', tier: 3, x: -4144, y: 1944, parentId: 'hub_face_8s', badge: '0° Master', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_face_8s_45', promptId: 'face_angle45_8s', title: 'Face 45° 8s', shortLabel: 'Face 45° 8s', icon: '↙️', iconPath: '/icons/skill_face_8s.svg', category: 'face', color: '#ec4899', tier: 3, x: -4129, y: 2117, parentId: 'hub_face_8s', badge: '45° Master', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_face_8s_90', promptId: 'face_angle90_8s', title: 'Face 90° 8s', shortLabel: 'Face 90° 8s', icon: '⬅️', iconPath: '/icons/skill_face_8s.svg', category: 'face', color: '#ec4899', tier: 3, x: -4134, y: 2291, parentId: 'hub_face_8s', badge: '90° Master', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_face_8s_135', promptId: 'face_angle135_8s', title: 'Face 8s 135°', shortLabel: 'Face 135° 8s', icon: '↘️', iconPath: '/icons/skill_face_8s.svg', category: 'face', color: '#ec4899', tier: 3, x: -4123, y: 2435, parentId: 'hub_face_8s', badge: '135° Glance', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },

  // ─── 2. HUB TỪNG BIỂU CẢM ĐƠN LẺ ───
  {
    id: 'hub_face_single',
    promptId: 'face_0_blink',
    title: 'Biểu Cảm Đơn Lẻ (Single Loops)',
    shortLabel: 'Từng Biểu Cảm',
    subtitle: 'Chớp mắt, cười, thoại, tức giận, ngạc nhiên, khóc, sợ, smirk...',
    icon: '🎭',
    iconPath: '/icons/skill_face_smile.svg',
    category: 'face',
    color: '#ec4899',
    tier: 2,
    x: -2207,
    y: 2270,
    parentId: 'pillar_face',
    isHub: true,
    badge: '4 GÓC ĐỘ',
  },

  // ─── 4 TRỤ GÓC ĐỘ TRUNG GIAN (0°, 45°, 90°, 135°) ───
  {
    id: 'hub_f_deg_0',
    promptId: 'face_0_blink',
    title: 'Biểu Cảm 0° Chính Diện',
    shortLabel: 'Góc 0°',
    subtitle: 'Tập hợp các biểu cảm góc nhìn trực diện',
    icon: '⬇️',
    iconPath: '/icons/skill_angle0.svg',
    category: 'face',
    color: '#ec4899',
    tier: 3,
    x: -1778,
    y: 2510,
    parentId: 'hub_face_single',
    isHub: true,
    badge: '17 BIỂU CẢM',
  },
  {
    id: 'hub_f_deg_45',
    promptId: 'face_45_talk',
    title: 'Biểu Cảm 45° Nghiêng Trái',
    shortLabel: 'Góc 45°',
    subtitle: 'Tập hợp các biểu cảm góc nhìn 3/4',
    icon: '↙️',
    iconPath: '/icons/skill_angle45.svg',
    category: 'face',
    color: '#ec4899',
    tier: 3,
    x: -2177,
    y: 2914,
    parentId: 'hub_face_single',
    isHub: true,
    badge: '16 BIỂU CẢM',
  },
  {
    id: 'hub_f_deg_90',
    promptId: 'face_90_profile',
    title: 'Biểu Cảm 90° Nhìn Ngang',
    shortLabel: 'Góc 90°',
    subtitle: 'Tập hợp các biểu cảm góc nhìn nghiêng mặt bên',
    icon: '⬅️',
    iconPath: '/icons/skill_angle90.svg',
    category: 'face',
    color: '#ec4899',
    tier: 3,
    x: -2936,
    y: 3150,
    parentId: 'hub_face_single',
    isHub: true,
    badge: '12 BIỂU CẢM',
  },
  {
    id: 'hub_f_deg_135',
    promptId: 'face_135_glance',
    title: 'Biểu Cảm 135° Ngoái Nhìn',
    shortLabel: 'Góc 135°',
    subtitle: 'Tập hợp các biểu cảm góc nhìn ngoái sau vai',
    icon: '↘️',
    iconPath: '/icons/skill_angle135.svg',
    category: 'face',
    color: '#ec4899',
    tier: 3,
    x: -2769,
    y: 2508,
    parentId: 'hub_face_single',
    isHub: true,
    badge: '9 BIỂU CẢM',
  },

  // ─── CÁC BIỂU CẢM THUỘC GÓC 0° (Nối vào hub_f_deg_0) ───
  { id: 'node_f0_blink', promptId: 'face_0_blink', title: 'Chớp Mắt 0°', shortLabel: '0° Chớp', icon: '👀', iconPath: '/icons/skill_face_blink.svg', category: 'face', color: '#ec4899', tier: 4, x: -1458, y: 2192, parentId: 'hub_f_deg_0', badge: '0° Blink', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_smile', promptId: 'face_0_smile', title: 'Mỉm Cười 0°', shortLabel: '0° Cười', icon: '😊', iconPath: '/icons/skill_face_smile.svg', category: 'face', color: '#ec4899', tier: 4, x: -1239, y: 2281, parentId: 'hub_f_deg_0', badge: '0° Smile', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_talk', promptId: 'face_0_talk', title: 'Nói Chuyện 0°', shortLabel: '0° Thoại', icon: '🗣️', iconPath: '/icons/skill_face_talk.svg', category: 'face', color: '#ec4899', tier: 4, x: -1066, y: 2371, parentId: 'hub_f_deg_0', badge: '0° Talk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_surp', promptId: 'face_0_surprised', title: 'Ngạc Nhiên 0°', shortLabel: '0° Ngạc Nhiên', icon: '😲', iconPath: '/icons/skill_face_surprised.svg', category: 'face', color: '#ec4899', tier: 4, x: -945, y: 2460, parentId: 'hub_f_deg_0', badge: '0° Surprise', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_sad', promptId: 'face_0_sad', title: 'Buồn Bã 0°', shortLabel: '0° Buồn', icon: '😢', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -836, y: 2546, parentId: 'hub_f_deg_0', badge: '0° Sad', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_angry', promptId: 'face_0_angry', title: 'Chiến Đấu 0°', shortLabel: '0° Giận', icon: '😠', iconPath: '/icons/skill_face_angry.svg', category: 'face', color: '#ec4899', tier: 4, x: -608, y: 2695, parentId: 'hub_f_deg_0', badge: '0° Angry', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_wink', promptId: 'face_0_wink', title: 'Nháy Mắt 0°', shortLabel: '0° Nháy', icon: '😉', iconPath: '/icons/skill_face_wink.svg', category: 'face', color: '#ec4899', tier: 4, x: -328, y: 2811, parentId: 'hub_f_deg_0', badge: '0° Wink', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_cry', promptId: 'face_0_cry', title: 'Khóc Lóc 0°', shortLabel: '0° Khóc', icon: '😭', iconPath: '/icons/skill_face_cry.svg', category: 'face', color: '#ec4899', tier: 4, x: -443, y: 2944, parentId: 'hub_f_deg_0', badge: '0° Cry', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_fear', promptId: 'face_0_fear', title: 'Sợ Hãi 0°', shortLabel: '0° Sợ', icon: '😨', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -665, y: 3145, parentId: 'hub_f_deg_0', badge: '0° Fear', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_smirk', promptId: 'face_0_smirk', title: 'Smirk 0°', shortLabel: '0° Nhếch Mép', icon: '😏', iconPath: '/icons/skill_face_smirk.svg', category: 'face', color: '#ec4899', tier: 4, x: -403, y: 3198, parentId: 'hub_f_deg_0', badge: '0° Smirk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_shy', promptId: 'face_0_shy', title: 'E Thẹn 0°', shortLabel: '0° E Thẹn', icon: '😳', iconPath: '/icons/skill_face_shy.svg', category: 'face', color: '#ec4899', tier: 4, x: -562, y: 3286, parentId: 'hub_f_deg_0', badge: '0° Shy', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_focus', promptId: 'face_0_focus', title: 'Quyết Tâm 0°', shortLabel: '0° Quyết Tâm', icon: '🔥', iconPath: '/icons/skill_face_focus.svg', category: 'face', color: '#ec4899', tier: 4, x: -748, y: 3353, parentId: 'hub_f_deg_0', badge: '0° Focus', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  // 5 Biểu cảm đặc biệt 0°
  { id: 'node_f0_funny', promptId: 'face_0_funny', title: 'Hài Hước 0°', shortLabel: 'Hài 0°', icon: '🤪', iconPath: '/icons/skill_face_funny.svg', category: 'face', color: '#ec4899', tier: 4, x: -714, y: 2629, parentId: 'hub_f_deg_0', badge: '0°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_sinister', promptId: 'face_0_sinister', title: 'Nham Hiểm 0°', shortLabel: 'Hiểm 0°', icon: '😈', iconPath: '/icons/skill_face_sinister.svg', category: 'face', color: '#ec4899', tier: 4, x: -467, y: 2743, parentId: 'hub_f_deg_0', badge: '0°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_mysterious', promptId: 'face_0_mysterious', title: 'Bí Hiểm 0°', shortLabel: 'Bí 0°', icon: '🎭', iconPath: '/icons/skill_face_mysterious.svg', category: 'face', color: '#ec4899', tier: 4, x: -192, y: 2883, parentId: 'hub_f_deg_0', badge: '0°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_disdain', promptId: 'face_0_disdain', title: 'Khinh Bỉ 0°', shortLabel: 'Khinh 0°', icon: '😒', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -572, y: 3021, parentId: 'hub_f_deg_0', badge: '0°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },
  { id: 'node_f0_dizzy', promptId: 'face_0_dizzy', title: 'Choáng Váng 0°', shortLabel: 'Choáng 0°', icon: '😵', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -266, y: 3075, parentId: 'hub_f_deg_0', badge: '0°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle0' },

  // ─── CÁC BIỂU CẢM THUỘC GÓC 45° (Nối vào hub_f_deg_45) ───
  { id: 'node_f45_talk', promptId: 'face_45_talk', title: 'Nói Chuyện 45°', shortLabel: '45° Thoại', icon: '🗣️', iconPath: '/icons/skill_face_talk.svg', category: 'face', color: '#ec4899', tier: 4, x: -1597, y: 2977, parentId: 'hub_f_deg_45', badge: '45° Talk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_surp', promptId: 'face_45_surprised', title: 'Ngạc Nhiên 45°', shortLabel: '45° Ngạc Nhiên', icon: '😲', iconPath: '/icons/skill_face_surprised.svg', category: 'face', color: '#ec4899', tier: 4, x: -1559, y: 3146, parentId: 'hub_f_deg_45', badge: '45° Surprise', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_angry', promptId: 'face_45_angry', title: 'Chiến Đấu 45°', shortLabel: '45° Giận', icon: '😠', iconPath: '/icons/skill_face_angry.svg', category: 'face', color: '#ec4899', tier: 4, x: -1674, y: 3303, parentId: 'hub_f_deg_45', badge: '45° Angry', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_smile', promptId: 'face_45_smile', title: 'Mỉm Cười 45°', shortLabel: '45° Cười', icon: '😊', iconPath: '/icons/skill_face_smile.svg', category: 'face', color: '#ec4899', tier: 4, x: -1582, y: 3465, parentId: 'hub_f_deg_45', badge: '45° Smile', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_blink', promptId: 'face_45_blink', title: 'Chớp Mắt 45°', shortLabel: '45° Chớp', icon: '👀', iconPath: '/icons/skill_face_blink.svg', category: 'face', color: '#ec4899', tier: 4, x: -1818, y: 3611, parentId: 'hub_f_deg_45', badge: '45° Blink', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_wink', promptId: 'face_45_wink', title: 'Nháy Mắt 45°', shortLabel: '45° Nháy', icon: '😉', iconPath: '/icons/skill_face_wink.svg', category: 'face', color: '#ec4899', tier: 4, x: -2140, y: 3722, parentId: 'hub_f_deg_45', badge: '45° Wink', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_cry', promptId: 'face_45_cry', title: 'Khóc Lóc 45°', shortLabel: '45° Khóc', icon: '😭', iconPath: '/icons/skill_face_cry.svg', category: 'face', color: '#ec4899', tier: 4, x: -2275, y: 3709, parentId: 'hub_f_deg_45', badge: '45° Cry', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_smirk', promptId: 'face_45_smirk', title: 'Smirk 45°', shortLabel: '45° Nhếch Mép', icon: '😏', iconPath: '/icons/skill_face_smirk.svg', category: 'face', color: '#ec4899', tier: 4, x: -2391, y: 3582, parentId: 'hub_f_deg_45', badge: '45° Smirk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_fear', promptId: 'face_45_fear', title: 'Sợ Hãi 45°', shortLabel: '45° Sợ', icon: '😨', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -2516, y: 3438, parentId: 'hub_f_deg_45', badge: '45° Fear', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_shy', promptId: 'face_45_shy', title: 'E Thẹn 45°', shortLabel: '45° E Thẹn', icon: '😳', iconPath: '/icons/skill_face_shy.svg', category: 'face', color: '#ec4899', tier: 4, x: -2486, y: 3175, parentId: 'hub_f_deg_45', badge: '45° Shy', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_sad', promptId: 'face_45_sad', title: 'Buồn Bã 45°', shortLabel: '45° Buồn', icon: '😢', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -2521, y: 3315, parentId: 'hub_f_deg_45', badge: '45° Sad', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  // 5 Biểu cảm đặc biệt 45°
  { id: 'node_f45_funny', promptId: 'face_45_funny', title: 'Hài Hước 45°', shortLabel: 'Hài 45°', icon: '🤪', iconPath: '/icons/skill_face_funny.svg', category: 'face', color: '#ec4899', tier: 4, x: -1722, y: 3069, parentId: 'hub_f_deg_45', badge: '45°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_sinister', promptId: 'face_45_sinister', title: 'Nham Hiểm 45°', shortLabel: 'Hiểm 45°', icon: '😈', iconPath: '/icons/skill_face_sinister.svg', category: 'face', color: '#ec4899', tier: 4, x: -1799, y: 3217, parentId: 'hub_f_deg_45', badge: '45°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_mysterious', promptId: 'face_45_mysterious', title: 'Bí Hiểm 45°', shortLabel: 'Bí 45°', icon: '🎭', iconPath: '/icons/skill_face_mysterious.svg', category: 'face', color: '#ec4899', tier: 4, x: -1788, y: 3376, parentId: 'hub_f_deg_45', badge: '45°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_disdain', promptId: 'face_45_disdain', title: 'Khinh Bỉ 45°', shortLabel: 'Khinh 45°', icon: '😒', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -1701, y: 3536, parentId: 'hub_f_deg_45', badge: '45°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },
  { id: 'node_f45_dizzy', promptId: 'face_45_dizzy', title: 'Choáng Váng 45°', shortLabel: 'Choáng 45°', icon: '😵', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -1948, y: 3674, parentId: 'hub_f_deg_45', badge: '45°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle45' },

  // ─── CÁC BIỂU CẢM THUỘC GÓC 90° (Nối vào hub_f_deg_90) ───
  { id: 'node_f90_prof', promptId: 'face_90_profile', title: 'Nghiêng 90° Chớp', shortLabel: '90° Chớp', icon: '👀', iconPath: '/icons/skill_angle90.svg', category: 'face', color: '#ec4899', tier: 4, x: -3131, y: 2982, parentId: 'hub_f_deg_90', badge: '90° Side', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_talk', promptId: 'face_90_talk', title: 'Nói Chuyện 90°', shortLabel: '90° Thoại', icon: '🗣️', iconPath: '/icons/skill_face_talk.svg', category: 'face', color: '#ec4899', tier: 4, x: -3437, y: 2981, parentId: 'hub_f_deg_90', badge: '90° Talk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_smile', promptId: 'face_90_smile', title: 'Mỉm Cười 90°', shortLabel: '90° Cười', icon: '😊', iconPath: '/icons/skill_face_smile.svg', category: 'face', color: '#ec4899', tier: 4, x: -3459, y: 3108, parentId: 'hub_f_deg_90', badge: '90° Smile', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_angry', promptId: 'face_90_angry', title: 'Giận Dữ 90°', shortLabel: '90° Giận', icon: '😠', iconPath: '/icons/skill_face_angry.svg', category: 'face', color: '#ec4899', tier: 4, x: -3536, y: 3313, parentId: 'hub_f_deg_90', badge: '90° Angry', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_surp', promptId: 'face_90_surprised', title: 'Ngạc Nhiên 90°', shortLabel: '90° Ngạc Nhiên', icon: '😲', iconPath: '/icons/skill_face_surprised.svg', category: 'face', color: '#ec4899', tier: 4, x: -3431, y: 3520, parentId: 'hub_f_deg_90', badge: '90° Shock', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_sad', promptId: 'face_90_sad', title: 'Buồn Bã 90°', shortLabel: '90° Buồn', icon: '😢', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -2998, y: 3606, parentId: 'hub_f_deg_90', badge: '90° Sad', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_cry', promptId: 'face_90_cry', title: 'Rơi Lệ 90°', shortLabel: '90° Lệ', icon: '😭', iconPath: '/icons/skill_face_cry.svg', category: 'face', color: '#ec4899', tier: 4, x: -3180, y: 3740, parentId: 'hub_f_deg_90', badge: '90° Tear', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  // 5 Biểu cảm đặc biệt 90°
  { id: 'node_f90_funny', promptId: 'face_90_funny', title: 'Hài Hước 90°', shortLabel: 'Hài 90°', icon: '🤪', iconPath: '/icons/skill_face_funny.svg', category: 'face', color: '#ec4899', tier: 4, x: -3595, y: 3048, parentId: 'hub_f_deg_90', badge: '90°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_sinister', promptId: 'face_90_sinister', title: 'Nham Hiểm 90°', shortLabel: 'Hiểm 90°', icon: '😈', iconPath: '/icons/skill_face_sinister.svg', category: 'face', color: '#ec4899', tier: 4, x: -3432, y: 3241, parentId: 'hub_f_deg_90', badge: '90°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_mysterious', promptId: 'face_90_mysterious', title: 'Bí Hiểm 90°', shortLabel: 'Bí 90°', icon: '🎭', iconPath: '/icons/skill_face_mysterious.svg', category: 'face', color: '#ec4899', tier: 4, x: -3706, y: 3182, parentId: 'hub_f_deg_90', badge: '90°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_disdain', promptId: 'face_90_disdain', title: 'Khinh Bỉ 90°', shortLabel: 'Khinh 90°', icon: '😒', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -3370, y: 3417, parentId: 'hub_f_deg_90', badge: '90°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },
  { id: 'node_f90_dizzy', promptId: 'face_90_dizzy', title: 'Choáng Váng 90°', shortLabel: 'Choáng 90°', icon: '😵', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -3277, y: 3596, parentId: 'hub_f_deg_90', badge: '90°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle90' },

  // ─── CÁC BIỂU CẢM THUỘC GÓC 135° (Nối vào hub_f_deg_135) ───
  { id: 'node_f135_glance', promptId: 'face_135_glance', title: 'Ngoái Nhìn 135°', shortLabel: '135° Ngoái', icon: '👀', iconPath: '/icons/skill_angle135.svg', category: 'face', color: '#ec4899', tier: 4, x: -3270, y: 2715, parentId: 'hub_f_deg_135', badge: '135° Glance', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_smile', promptId: 'face_135_smile', title: 'Ngoái Cười 135°', shortLabel: '135° Cười', icon: '😊', iconPath: '/icons/skill_face_smile.svg', category: 'face', color: '#ec4899', tier: 4, x: -2935, y: 2780, parentId: 'hub_f_deg_135', badge: '135° Smile', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_talk', promptId: 'face_135_talk', title: 'Ngoái Thoại 135°', shortLabel: '135° Thoại', icon: '🗣️', iconPath: '/icons/skill_face_talk.svg', category: 'face', color: '#ec4899', tier: 4, x: -3431, y: 2436, parentId: 'hub_f_deg_135', badge: '135° Talk', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_alert', promptId: 'face_135_alert', title: 'Cảnh Giác 135°', shortLabel: '135° Giác', icon: '👁️', iconPath: '/icons/skill_face_alert.svg', category: 'face', color: '#ec4899', tier: 4, x: -3338, y: 2368, parentId: 'hub_f_deg_135', badge: '135° Alert', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  // 5 Biểu cảm đặc biệt 135°
  { id: 'node_f135_funny', promptId: 'face_135_funny', title: 'Hài Hước 135°', shortLabel: 'Hài 135°', icon: '🤪', iconPath: '/icons/skill_face_funny.svg', category: 'face', color: '#ec4899', tier: 4, x: -3416, y: 2659, parentId: 'hub_f_deg_135', badge: '135°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_sinister', promptId: 'face_135_sinister', title: 'Nham Hiểm 135°', shortLabel: 'Hiểm 135°', icon: '😈', iconPath: '/icons/skill_face_sinister.svg', category: 'face', color: '#ec4899', tier: 4, x: -3359, y: 2572, parentId: 'hub_f_deg_135', badge: '135°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_mysterious', promptId: 'face_135_mysterious', title: 'Bí Hiểm 135°', shortLabel: 'Bí 135°', icon: '🎭', iconPath: '/icons/skill_face_mysterious.svg', category: 'face', color: '#ec4899', tier: 4, x: -3501, y: 2499, parentId: 'hub_f_deg_135', badge: '135°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_disdain', promptId: 'face_135_disdain', title: 'Khinh Bỉ 135°', shortLabel: 'Khinh 135°', icon: '😒', iconPath: '/icons/skill_face_sad.svg', category: 'face', color: '#ec4899', tier: 4, x: -3223, y: 2266, parentId: 'hub_f_deg_135', badge: '135°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
  { id: 'node_f135_dizzy', promptId: 'face_135_dizzy', title: 'Choáng Váng 135°', shortLabel: 'Choáng 135°', icon: '😵', iconPath: '/icons/skill_face_fear.svg', category: 'face', color: '#ec4899', tier: 4, x: -3069, y: 2151, parentId: 'hub_f_deg_135', badge: '135°', promptType: 'video' , generationMode: 'image_to_video', aspectRatio: '1:1', refAngleImageId: 'angle135' },
];
