import { SkillTreeNode } from '../types';

export const LOCOMOTION_NODES: SkillTreeNode[] = [
  // ─── TIER 1: TRỤ DI CHUYỂN ───
  {
    id: 'pillar_locomotion',
    promptId: 'walk_angle0',
    title: 'Trụ Di Chuyển (Locomotion)',
    shortLabel: 'Đi Bộ & Chạy',
    subtitle: 'Chu kỳ bước chân và chạy nước rút',
    icon: '🚶',
    iconPath: '/icons/pillar_locomotion.svg',
    category: 'walk',
    color: '#34d399',
    tier: 1,
    x: 400,
    y: 206,
    parentId: 'root_master',
    isHub: true,
    badge: '10 PROMPTS',
  },

  // ─── 1. HUB ĐI BỘ ───
  {
    id: 'hub_walk',
    promptId: 'walk_angle0',
    title: 'Nhánh Đi Bộ (Walk Cycles)',
    shortLabel: 'Đi Bộ',
    subtitle: 'Chu kỳ bước chân 5 góc độ cơ bản',
    icon: '🚶',
    iconPath: '/icons/skill_walk.svg',
    category: 'walk',
    color: '#34d399',
    tier: 2,
    x: 620,
    y: -261,
    parentId: 'pillar_locomotion',
    isHub: true,
    badge: 'WALK 5 GÓC',
  },
  { id: 'node_walk_0', promptId: 'walk_angle0', title: 'Đi Bộ 0°', shortLabel: 'Walk 0°', icon: '⬇️', iconPath: '/icons/skill_walk.svg', category: 'walk', color: '#34d399', tier: 3, x: 657, y: -827, parentId: 'hub_walk', badge: '0°', promptType: 'video' },
  { id: 'node_walk_45', promptId: 'walk_angle45', title: 'Đi Bộ 45°', shortLabel: 'Walk 45°', icon: '↙️', iconPath: '/icons/skill_walk.svg', category: 'walk', color: '#34d399', tier: 3, x: 809, y: -744, parentId: 'hub_walk', badge: '45°', promptType: 'video' },
  { id: 'node_walk_90', promptId: 'walk_angle90', title: 'Đi Bộ 90°', shortLabel: 'Walk 90°', icon: '⬅️', iconPath: '/icons/skill_walk.svg', category: 'walk', color: '#34d399', tier: 3, x: 928, y: -665, parentId: 'hub_walk', badge: '90°', promptType: 'video' },
  { id: 'node_walk_135', promptId: 'walk_angle135', title: 'Đi Bộ 135°', shortLabel: 'Walk 135°', icon: '↘️', iconPath: '/icons/skill_walk.svg', category: 'walk', color: '#34d399', tier: 3, x: 1018, y: -578, parentId: 'hub_walk', badge: '135°', promptType: 'video' },
  { id: 'node_walk_180', promptId: 'walk_angle180', title: 'Đi Bộ 180°', shortLabel: 'Walk 180°', icon: '⬆️', iconPath: '/icons/skill_walk.svg', category: 'walk', color: '#34d399', tier: 3, x: 1066, y: -500, parentId: 'hub_walk', badge: '180°', promptType: 'video' },

  // ─── 2. HUB CHẠY ───
  {
    id: 'hub_run',
    promptId: 'run_angle0',
    title: 'Nhánh Chạy (Run Cycles)',
    shortLabel: 'Chạy Nhanh',
    subtitle: 'Chu kỳ chạy nước rút 5 góc độ cơ bản',
    icon: '🏃',
    iconPath: '/icons/skill_run.svg',
    category: 'walk',
    color: '#34d399',
    tier: 2,
    x: 1223,
    y: -230,
    parentId: 'pillar_locomotion',
    isHub: true,
    badge: 'RUN 5 GÓC',
  },
  { id: 'node_run_0', promptId: 'run_angle0', title: 'Chạy 0°', shortLabel: 'Run 0°', icon: '⬇️', iconPath: '/icons/skill_run.svg', category: 'walk', color: '#34d399', tier: 3, x: 1459, y: -426, parentId: 'hub_run', badge: '0°', promptType: 'video' },
  { id: 'node_run_45', promptId: 'run_angle45', title: 'Chạy 45°', shortLabel: 'Run 45°', icon: '↙️', iconPath: '/icons/skill_run.svg', category: 'walk', color: '#34d399', tier: 3, x: 1597, y: -361, parentId: 'hub_run', badge: '45°', promptType: 'video' },
  { id: 'node_run_90', promptId: 'run_angle90', title: 'Chạy 90°', shortLabel: 'Run 90°', icon: '⬅️', iconPath: '/icons/skill_run.svg', category: 'walk', color: '#34d399', tier: 3, x: 1695, y: -301, parentId: 'hub_run', badge: '90°', promptType: 'video' },
  { id: 'node_run_135', promptId: 'run_angle135', title: 'Chạy 135°', shortLabel: 'Run 135°', icon: '↘️', iconPath: '/icons/skill_run.svg', category: 'walk', color: '#34d399', tier: 3, x: 1757, y: -186, parentId: 'hub_run', badge: '135°', promptType: 'video' },
  { id: 'node_run_180', promptId: 'run_angle180', title: 'Chạy 180°', shortLabel: 'Run 180°', icon: '⬆️', iconPath: '/icons/skill_run.svg', category: 'walk', color: '#34d399', tier: 3, x: 1826, y: -106, parentId: 'hub_run', badge: '180°', promptType: 'video' },
];
