import {
  Character2DPartType,
  StandardCropPreset,
} from '../../../types/scene2d';

// ─── Standard Slicing / Bounding Box Presets ─────────────────────
export const STANDARD_CROP_PRESETS: StandardCropPreset[] = [
  {
    id: 'crop_dau',
    label: 'Đầu & Sọ (512x512)',
    category: 'nhan_vat',
    slot: 'dau',
    width: 512,
    height: 512,
    aspectRatio: 1.0,
    suggestedPivot: [0.5, 0.85],
    description: 'Bao gồm phần đầu, cằm, tai, không có tóc phủ.',
  },
  {
    id: 'crop_mat',
    label: 'Cặp Mắt (128x64)',
    category: 'nhan_vat',
    slot: 'mat',
    width: 128,
    height: 64,
    aspectRatio: 2.0,
    suggestedPivot: [0.5, 0.5],
    description: 'Chứa mắt mở hoặc nhắm để đổi trạng thái chớp mắt.',
  },
  {
    id: 'crop_mieng',
    label: 'Khẩu Hình Miệng (128x64)',
    category: 'nhan_vat',
    slot: 'mieng',
    width: 128,
    height: 64,
    aspectRatio: 2.0,
    suggestedPivot: [0.5, 0.5],
    description: 'Khẩu hình nói chuyện A/I/U/E/O, cười, hoặc ngậm miệng.',
  },
  {
    id: 'crop_mui',
    label: 'Mũi (64x64)',
    category: 'nhan_vat',
    slot: 'mui',
    width: 64,
    height: 64,
    aspectRatio: 1.0,
    suggestedPivot: [0.5, 0.5],
    description: 'Sống mũi thẳng hoặc góc nghiêng 3/4.',
  },
  {
    id: 'crop_toc_truoc',
    label: 'Tóc Mái / Tóc Trước (512x512)',
    category: 'nhan_vat',
    slot: 'toc_truoc',
    width: 512,
    height: 512,
    aspectRatio: 1.0,
    suggestedPivot: [0.5, 0.2],
    description: 'Lớp tóc mái phía trước mặt (Z-index cao nhất phần đầu).',
  },
  {
    id: 'crop_toc_sau',
    label: 'Tóc Dài Phía Sau (512x512)',
    category: 'nhan_vat',
    slot: 'toc_sau',
    width: 512,
    height: 512,
    aspectRatio: 1.0,
    suggestedPivot: [0.5, 0.2],
    description: 'Lớp tóc dài xõa sau lưng (Z-index thấp nhất dưới thân).',
  },
  {
    id: 'crop_than',
    label: 'Thân & Ngực Bụng (512x768)',
    category: 'nhan_vat',
    slot: 'than_co_ban',
    width: 512,
    height: 768,
    aspectRatio: 0.667,
    suggestedPivot: [0.5, 0.8],
    description: 'Phần thân mình cơ bản làm trụ gắn các chi.',
  },
  {
    id: 'crop_canh_tay',
    label: 'Cánh Tay Trên (256x512)',
    category: 'nhan_vat',
    slot: 'canh_tay_trai',
    width: 256,
    height: 512,
    aspectRatio: 0.5,
    suggestedPivot: [0.5, 0.15],
    description: 'Từ khớp vai đến khuỷu tay.',
  },
  {
    id: 'crop_cang_tay',
    label: 'Cẳng Tay & Bàn Tay (256x512)',
    category: 'nhan_vat',
    slot: 'cang_tay_trai',
    width: 256,
    height: 512,
    aspectRatio: 0.5,
    suggestedPivot: [0.5, 0.15],
    description: 'Từ khuỷu tay đến bàn tay cầm nắm vũ khí.',
  },
  {
    id: 'crop_cang_chan',
    label: 'Chân & Bàn Chân (256x512)',
    category: 'nhan_vat',
    slot: 'cang_chan_trai',
    width: 256,
    height: 512,
    aspectRatio: 0.5,
    suggestedPivot: [0.5, 0.1],
    description: 'Từ hông hoặc đầu gối xuống bàn chân.',
  },
  {
    id: 'crop_trang_phuc',
    label: 'Trang Phục / Đạo Bào (512x768)',
    category: 'nhan_vat',
    slot: 'trang_phuc',
    width: 512,
    height: 768,
    aspectRatio: 0.667,
    suggestedPivot: [0.5, 0.5],
    description: 'Áo dài, giáp trụ, tà áo bay phủ ngoài thân.',
  },
  {
    id: 'crop_vu_khi',
    label: 'Vũ Khí & Đạo Cụ (512x512)',
    category: 'nhan_vat',
    slot: 'vu_khi',
    width: 512,
    height: 512,
    aspectRatio: 1.0,
    suggestedPivot: [0.2, 0.8],
    description: 'Kiếm, đao, thương, trượng, quạt, pháp bảo.',
  },
  {
    id: 'crop_map_layer',
    label: 'Lớp Bản Đồ Parallax (1920x1080)',
    category: 'ban_do',
    slot: 'map_layer',
    width: 1920,
    height: 1080,
    aspectRatio: 1.778,
    suggestedPivot: [0.5, 0.5],
    description: 'Ảnh kích thước chuẩn 16:9 cho từng tầng bản đồ.',
  },
];

// ─── Default 2D Part Hierarchy & Pivot Presets ───────────────────
export const PART_HIERARCHY_CONFIG: Record<
  Character2DPartType,
  { label: string; defaultZ: number; defaultZDepth3D: number; defaultPivot: [number, number]; defaultOffset: [number, number] }
> = {
  toc_sau: { label: 'Tóc Sau', defaultZ: 1, defaultZDepth3D: 1, defaultPivot: [0.5, 0.15], defaultOffset: [0, -165] },
  than_co_ban: { label: 'Thân Cơ Bản', defaultZ: 2, defaultZDepth3D: 2, defaultPivot: [0.5, 0.5], defaultOffset: [0, 0] },
  dui_trai: { label: 'Đùi Trái', defaultZ: 2, defaultZDepth3D: 2, defaultPivot: [0.5, 0.1], defaultOffset: [-22, 60] },
  dui_phai: { label: 'Đùi Phải', defaultZ: 2, defaultZDepth3D: 2, defaultPivot: [0.5, 0.1], defaultOffset: [22, 60] },
  cang_chan_trai: { label: 'Cẳng Chân Trái', defaultZ: 3, defaultZDepth3D: 2, defaultPivot: [0.5, 0.1], defaultOffset: [-22, 75] },
  cang_chan_phai: { label: 'Cẳng Chân Phải', defaultZ: 3, defaultZDepth3D: 2, defaultPivot: [0.5, 0.1], defaultOffset: [22, 75] },
  trang_phuc: { label: 'Trang Phục', defaultZ: 4, defaultZDepth3D: 4, defaultPivot: [0.5, 0.5], defaultOffset: [0, 5] },
  canh_tay_trai: { label: 'Cánh Tay Trái', defaultZ: 5, defaultZDepth3D: 5, defaultPivot: [0.8, 0.15], defaultOffset: [-55, -60] },
  cang_tay_trai: { label: 'Cẳng Tay Trái', defaultZ: 5, defaultZDepth3D: 6, defaultPivot: [0.8, 0.2], defaultOffset: [-65, 10] },
  ban_tay_trai: { label: 'Bàn Tay Trái', defaultZ: 5, defaultZDepth3D: 7, defaultPivot: [0.5, 0.2], defaultOffset: [-70, 50] },
  dau: { label: 'Đầu & Cằm', defaultZ: 6, defaultZDepth3D: 8, defaultPivot: [0.5, 0.85], defaultOffset: [0, -100] },
  khuon_mat: { label: 'Khuôn Mặt', defaultZ: 7, defaultZDepth3D: 9, defaultPivot: [0.5, 0.5], defaultOffset: [0, -135] },
  khuon_mat_no_face: { label: 'Mặt Trần (No Face)', defaultZ: 7, defaultZDepth3D: 9, defaultPivot: [0.5, 0.5], defaultOffset: [0, -135] },
  mat: { label: 'Đôi Mắt Tổng Hợp', defaultZ: 8, defaultZDepth3D: 10, defaultPivot: [0.5, 0.5], defaultOffset: [0, -140] },
  trong_trang: { label: 'Tròng Trắng (Sclera)', defaultZ: 7.5, defaultZDepth3D: 9.5, defaultPivot: [0.5, 0.5], defaultOffset: [0, -140] },
  trong_den_iris: { label: 'Mống Mắt & Con Ngươi (Iris)', defaultZ: 8, defaultZDepth3D: 10, defaultPivot: [0.5, 0.5], defaultOffset: [0, -140] },
  diem_sang_mat: { label: 'Điểm Sáng / Highlight Mắt', defaultZ: 8.5, defaultZDepth3D: 10.2, defaultPivot: [0.5, 0.5], defaultOffset: [0, -140] },
  mi_mat: { label: 'Mi Mắt & Chớp Mắt', defaultZ: 9, defaultZDepth3D: 10.8, defaultPivot: [0.5, 0.5], defaultOffset: [0, -140] },
  long_may: { label: 'Lông Mày', defaultZ: 8, defaultZDepth3D: 10.5, defaultPivot: [0.5, 0.5], defaultOffset: [0, -145] },
  mui: { label: 'Sống Mũi', defaultZ: 8, defaultZDepth3D: 11, defaultPivot: [0.5, 0.5], defaultOffset: [0, -125] },
  doi_tai: { label: 'Đôi Tai', defaultZ: 7, defaultZDepth3D: 8.5, defaultPivot: [0.5, 0.5], defaultOffset: [0, -135] },
  mui_tai: { label: 'Mũi & Đôi Tai', defaultZ: 8, defaultZDepth3D: 11, defaultPivot: [0.5, 0.5], defaultOffset: [0, -125] },
  mieng: { label: 'Miệng (Khẩu hình)', defaultZ: 8, defaultZDepth3D: 10, defaultPivot: [0.5, 0.5], defaultOffset: [0, -110] },
  toc_truoc: { label: 'Tóc Mái Trước', defaultZ: 9, defaultZDepth3D: 12, defaultPivot: [0.5, 0.1], defaultOffset: [0, -170] },
  canh_tay_phai: { label: 'Cánh Tay Phải', defaultZ: 10, defaultZDepth3D: 5, defaultPivot: [0.2, 0.15], defaultOffset: [55, -60] },
  cang_tay_phai: { label: 'Cẳng Tay Phải', defaultZ: 10, defaultZDepth3D: 6, defaultPivot: [0.2, 0.2], defaultOffset: [65, 10] },
  ban_tay_phai: { label: 'Bàn Tay Phải', defaultZ: 10, defaultZDepth3D: 7, defaultPivot: [0.5, 0.2], defaultOffset: [70, 50] },
  tay_chan: { label: 'Tứ Chi & Bàn Tay', defaultZ: 10, defaultZDepth3D: 7, defaultPivot: [0.5, 0.2], defaultOffset: [0, 20] },
  ao_choang: { label: 'Áo Choàng / Tà Áo', defaultZ: 1, defaultZDepth3D: 0.5, defaultPivot: [0.5, 0.1], defaultOffset: [0, 20] },
  vu_khi: { label: 'Vũ Khí / Pháp Bảo', defaultZ: 11, defaultZDepth3D: 13, defaultPivot: [0.5, 0.2], defaultOffset: [72, 35] },
};
